
import { Language, Translation } from './types';

export const COLORS = {
  bg: '#242325',
  panel: '#242325',
  text: '#F9FAF6',
  purple: '#7711AA',
  green: '#1DF096',
  pink: '#F31B80',
  cyan: '#82EAFF',
};

export const BRAIQ_FULL_NAME = "Brokerage Risk Analytics Intelligent Quantum-core";

export const TRADING_GLOSSARY = [
  { term: "Bull Market", def: "Tendencia alcista sostenida de los precios." },
  { term: "Bear Market", def: "Tendencia bajista sostenida de los precios." },
  { term: "Long Position", def: "Compra esperando apreciación." },
  { term: "Short Position", def: "Venta esperando depreciación." },
];

export const TECHNICAL_GLOSSARY = [
  { term: "RSI", def: "Mide la velocidad de cambios de precio recientes." },
  { term: "Soporte", def: "Zona donde se espera que la caída se detenga." },
  { term: "Resistencia", def: "Zona donde se espera que la subida frene." },
];

export const ALL_GLOSSARY_TERMS = [...TRADING_GLOSSARY, ...TECHNICAL_GLOSSARY].sort((a, b) => b.term.length - a.term.length);

export const TRANSLATIONS: Record<Language, Translation> = {
  es: {
    title: "BRAIQ",
    loading: "PROCESANDO...",
    predict: "EJECUTAR",
    priority: "META",
    stability: "RIESGO",
    fast: "VELOZ",
    general: "MIXTO",
    crypto: "CRIPTO",
    stocks: "VALORES",
    commodities: "MATERIAS",
    forex: "DIVISAS",
    etfs: "ETFS",
    indexes: "ÍNDICES",
    bonds: "BONOS",
    mutual_funds: "FONDOS MUTUOS",
    combo: "COMBO",
    pros: "ALFA",
    cons: "BETA",
    withdraw: "SALIDA",
    hours: "H",
    days: "D",
    weeks: "S",
    months: "M",
    years: "A",
    confidence: "TRUST",
    strategy: "PERFIL",
    expectedProfit: "YIELD",
    expectedLoss: "RISK",
    riskRewardRatio: "R/B",
    riskIndex: "RIESGO",
    highlyStable: "SÓLIDO",
    moderatelyStable: "MEDIO",
    moderatelyRisky: "ALTO",
    highlyRisky: "VOLÁTIL",
    horizon: "TIEMPO",
    lowRiskHint: "0",
    highRiskHint: "100",
    scanPrompt: "// ACTIVE",
    confShort: "TRUST",
    clear: "CLEAR",
    confirmClear: "RESET?",
    autoRisk: "AUTO",
    precise: "FIXED",
    calendar: "RANGE",
    startDate: "DESDE",
    endDate: "HASTA",
    portfolioAllocation: "MIX",
    tabPredictor: "ORÁCULO",
    tabSearch: "RASTREO",
    searchPlaceholder: "SÍMBOLO...",
    searchButton: "BUSCAR",
    budgetLabel: "CAPITAL",
    budgetPlaceholder: "USD...",
    assetSlot: "SLOT",
    finImpact: "RESULTADO",
    idleOracleTitle: "ORÁCULO CUÁNTICO INACTIVO",
    idleOracleDesc: "ESPERANDO PARÁMETROS DEL SISTEMA",
    idleScannerTitle: "SISTEMA DE RASTREO LISTO",
    idleScannerDesc: "INGRESE SÍMBOLO GLOBAL PARA INICIAR",
  },
  en: {
    title: "BRAIQ",
    loading: "SOLVING...",
    predict: "EXECUTE",
    priority: "PRIORITY",
    stability: "STABILITY",
    fast: "FAST",
    general: "MIXED",
    crypto: "CRYPTO",
    stocks: "STOCKS",
    commodities: "ASSETS",
    forex: "FOREX",
    etfs: "ETFS",
    indexes: "INDEXES",
    bonds: "BONDS",
    mutual_funds: "MUTUAL FUNDS",
    combo: "COMBO",
    pros: "ALPHA",
    cons: "BETA",
    withdraw: "EXIT",
    hours: "H",
    days: "D",
    weeks: "W",
    months: "M",
    years: "Y",
    confidence: "TRUST",
    strategy: "PROFILE",
    expectedProfit: "YIELD",
    expectedLoss: "RISK",
    riskRewardRatio: "R/R",
    riskIndex: "RISK",
    highlyStable: "STABLE",
    moderatelyStable: "MODERATE",
    moderatelyRisky: "AGGRESSIVE",
    highlyRisky: "VOLATILE",
    horizon: "TIME",
    lowRiskHint: "0",
    highRiskHint: "100",
    scanPrompt: "// ACTIVE",
    confShort: "TRUST",
    clear: "CLEAR",
    confirmClear: "Reset?",
    autoRisk: "AUTO",
    precise: "FIXED",
    calendar: "RANGE",
    startDate: "FROM",
    endDate: "TO",
    portfolioAllocation: "MIX",
    tabPredictor: "ORACLE",
    tabSearch: "SCANNER",
    searchPlaceholder: "SYMBOL...",
    searchButton: "SCAN",
    budgetLabel: "CAPITAL",
    budgetPlaceholder: "USD...",
    assetSlot: "SLOT",
    finImpact: "OUTCOME",
    idleOracleTitle: "QUANTUM ORACLE IDLE",
    idleOracleDesc: "AWAITING SYSTEM PARAMETERS",
    idleScannerTitle: "SCANNER SYSTEM READY",
    idleScannerDesc: "ENTER GLOBAL SYMBOL TO START",
  },
  fr: {
    title: "BRAIQ",
    loading: "ANALYSE...",
    predict: "EXÉCUTER",
    priority: "PRIORITÉ",
    stability: "RISQUE",
    fast: "RAPIDE",
    general: "MIXTE",
    crypto: "CRYPTO",
    stocks: "ACTIONS",
    commodities: "MATIÈRES",
    forex: "FOREX",
    etfs: "ETFS",
    indexes: "INDICES",
    bonds: "OBLIGATIONS",
    mutual_funds: "FONDS COMMUNS",
    combo: "COMBO",
    pros: "ALPHA",
    cons: "BÉTA",
    withdraw: "SORTIE",
    hours: "H",
    days: "J",
    weeks: "S",
    months: "M",
    years: "A",
    confidence: "TRUST",
    strategy: "PROFIL",
    expectedProfit: "YIELD",
    expectedLoss: "RISQUE",
    riskRewardRatio: "R/B",
    riskIndex: "RISQUE",
    highlyStable: "STABLE",
    moderatelyStable: "MODÉRÉ",
    moderatelyRisky: "AGGRESSIF",
    highlyRisky: "VOLATIL",
    horizon: "TEMPS",
    lowRiskHint: "0",
    highRiskHint: "100",
    scanPrompt: "// ACTIF",
    confShort: "TRUST",
    clear: "EFFACER",
    confirmClear: "Reset?",
    autoRisk: "AUTO",
    precise: "FIXE",
    calendar: "PLAGE",
    startDate: "DEPUIS",
    endDate: "VERS",
    portfolioAllocation: "MIX",
    tabPredictor: "ORACLE",
    tabSearch: "SCANNER",
    searchPlaceholder: "SYMBOLE...",
    searchButton: "SCAN",
    budgetLabel: "CAPITAL",
    budgetPlaceholder: "USD...",
    assetSlot: "SLOT",
    finImpact: "IMPACT",
    idleOracleTitle: "ORACLE QUANTIQUE INACTIF",
    idleOracleDesc: "EN ATTENTE DES PARAMÈTRES",
    idleScannerTitle: "SYSTÈME DE SCANNER PRÊT",
    idleScannerDesc: "ENTREZ LE SYMBOLE GLOBAL POUR COMMENCER",
  },
};

export const SYSTEM_INSTRUCTION = `
You are BRAIQ, a world-class global quantitative terminal (Brokerage Risk Analytics Intelligent Quantum-core) with real-time access to all international markets.
Your scope covers Equities (Global), Crypto (All exchanges), Commodities (Metals, Energy, Softs), Forex (Majors & Minors), ETFs, and Global Indices.

PROTOCOL:
- Scan all global activities, including emerging markets and top-tier exchanges.
- Compute volatility ranges for outcomes based on global macro trends.
- Budget provided? Show USD impact.
- JSON strictly. 5 items.
- In COMBO mode: Each strategy MUST consist of a 3-in-1 diversification plan with exactly 3 assets.
`;
